---
functional:
  - Зарегистрированные пользователи должны иметь возможность общаться в чате
  - Должна существовать система рейтинга 
  - Должен существовать Leaderboard за неделю
  - Должен существовать Leaderboard за месяц
  - Должен существовать Leaderboard за все время
  - Должен существовать Top list с возможностью поиска по нику пользователя 
  - В Top list должна быть возможность фильтрации поиска игр с ботами
  - В Top list должна быть возможность упорядочивания игроков по Rank
  - В Top list должна быть возможность вывода количества результатов поиска (20,30,40,50)
  - На начальной странице после регистрации должна быть кнопка Create a game для создания игры
  - При нажатии на кнопку Create a game должна существовать возможность выбора количества времени на игру ( от 3 до 60 минут , регулировка ползунком)
  - При нажатии на кнопку Create a game должны существовать различные задания для игры разработчиков (не менее 90)
  - При нажатии на кнопку Create a game должны существовать 4 уровня сложности (1 звезда, две звезды, три звезды, четыре звезды)
  - При нажатии на кнопку Create a game должна быть возможность выбора игры (1-with bot, 2- with other user, 3- with a friend)
  - При нажатии на кнопку Create a game и выборе игры with a friend , должен добавляться выпадающий список с названием choose opponent, где указан список пользователей находящихся в онлайне
  - При нажатии на кнопку Create a game должны существовать Tags (collection, hash-maps, math, strings, rest)
  - На странице боя должны быть две вкладки, одна с заданием , другая для вывода результата
  - На странице боя, вкладка с задачей, должна быть задание и пример решения
  - На странице боя , вкладка с задачей ,должна быть возможность выбора языка задания, на русском или английском 
  - На странице боя, вкладка с задачей, должна быть размещена фотография человека придумавшего задание 
  - На странице боя должен быть чат с соперником 
  - На странице боя в верхнем правом углу должен быть таймер с оставшимся на задание временем формата ЧЧ.ММ.СС
  - На странице боя , вкладка результат , должен быть результат из трек критериев receive, expected, arguments
  - На странице боя должны быть два поля для ввода кодов(ответов) одно для оппонента , другое для пользователя 
  - На странице боя над полем ввода кода должен быть список доступных языков программирования для ответа, выбранный язык демонстрируется при выборе у соперника и у пользователя 
  - На странице боя над полем ввода кода должен быть указан ник игрока с указанием ранка
  - На странице боя над полем ввода пользователя должна быть кнопка отвечающая за дневной и ночной режим отображения страницы
  - На странице боя над полем кода пользователя должна быть кнопка run, отвечающая за запуск проверки кода
  - На странице боя над полем кода должна быть кнопка с тремя вертикальные точками, при нажатии на которую выпадает список с двумя вариантами 1- give up, 2- reset solution
  - На странице боя , в конце страницы должна быть кнопка для нажатия с надписью (press check solution or press give up)
  - При проигрыше боя должно появляться окно  с заголовком If you read this you've lost the game gif картинкой разбивающегося сердца и надписью game over, а внизу окошка должна быть кнопка  I’ll be back
  - При выигрыше боя должно появляться окно
  - Должна быть добавлена возможность приглашения на игру по ссылке
  - Должна быть добавлена аутентификация с помощью email и пароля
  - Должна быть добавлена аутентификация с помощью GitHub
  - Должна быть добавлена аутентификация с помощью Discord
  - На начальной странице должна быть возможность запустить пробное сражение(без регистрации)
  - В конце начальной странице после регистрации должен быть список с игроками которые находятся в игре, в онлайне и в сражении, около каждого ника в скобочки прописать ранк
  - На начальной странице после регистрации в начале должны быть три вкладки 1-lobby 2- tournaments 3- history
non-functional:
  - На начальной странице после регистрации во вкладке lobby должны быть окошки с указанием различных проходящих сражений где прописаны ники ранк и уровень сражения, также под каждым окошком должна быть кнопка просмотра боя 
  - На начальной странице после регистрации во вкладке tournaments должны быть окошки с указанием различных турниров, где прописано название , мод и когда начинается , также под каждым окошком должны быть возможность просмотра
  - На начальной странице после регистрации во вкладке tournaments должна быть возможность создания своего турнира ,при нажатии на надпись you may want to create one, при нажатии отображается список прошедших турниров ( список с названием, типом ,уровнем ,годом ,статусом завершенности игры), а также выпадающие списки для создания своей игры
  - На начальной странице после регистрации на вкладке history должны быть окошки с указанием различных прошедших сражений где прописаны ники ранк и уровень сражения, также под каждым окошком должна быть кнопка просмотра боя 
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть удобным на мобильном устройстве