---
functional:
  - Пользователи должны иметь возможность общаться
  - Должна существовать система рейтинга
  - Пользователь должен легко создавать пробные игры с ботом, а также с реальным игроком
  - Должна существовать возможность выбора количества времени на игру
  - Должны существовать различные задания для игры разработчиков (не менее 90)
  - Должна быть добавлена возможность приглашения на игру по ссылке
  - Должна быть добавлена аутентификация с помощью GitHub и Discord
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть удобным на мобильном устройстве
